const OLLsolutions = [
  [
    [
      [false, true, false, false, false],
      [false, false, true, true, false],
      [false, true, true, false, true],
      [false, false, false, true, false],
      [false, true, true, false, false],
    ],
    "29",
    "Awkward Shape",
    "R U R' U' R U' R' F' U' F R U R'",
  ],
  [
    [
      [false, false, false, false, false],
      [true, false, true, false, true],
      [false, true, true, false, true],
      [false, true, false, true, false],
      [false, false, true, false, false],
    ],
    "30",
    "Awkward Shape",
    "F R' F R2 U' R' U' R U R' F2",
  ],
  [
    [
      [false, true, false, true, false],
      [false, false, true, false, false],
      [false, true, true, false, true],
      [false, true, false, true, false],
      [false, false, true, false, false],
    ],
    "41",
    "Awkward Shape",
    "R U R' U R U2 R' F R U R' U' F'",
  ],
  [
    [
      [false, false, true, false, false],
      [false, true, false, true, false],
      [false, true, true, false, true],
      [false, false, true, false, false],
      [false, true, false, true, false],
    ],
    "42",
    "Awkward Shape",
    "R' U' R U' R' U2 R F R U R' U' F'",
  ],
  [
    [
      [false, true, true, false, false],
      [false, false, false, true, false],
      [false, true, true, true, false],
      [false, true, false, false, true],
      [false, false, true, false, false],
    ],
    "39",
    "Big Lightning Bolt",
    "L F' L' U' L U F U' L'",
  ],
  [
    [
      [false, false, true, true, false],
      [false, true, false, false, false],
      [false, true, true, true, false],
      [true, false, false, true, false],
      [false, false, true, false, false],
    ],
    "40",
    "Big Lightning Bolt",
    "R' F R U R' U' F' U R",
  ],
  [
    [
      [false, false, true, false, false],
      [true, false, false, false, true],
      [false, true, true, true, false],
      [false, true, false, true, false],
      [false, false, true, false, false],
    ],
    "34",
    "C Shape",
    "R U R2 U' R' F R U R U' F'",
  ],
  [
    [
      [false, false, false, false, false],
      [false, true, true, false, true],
      [true, false, true, false, true],
      [false, true, true, false, true],
      [false, false, false, false, false],
    ],
    "46",
    "C Shape",
    "R' U' R' F R F' U R",
  ],
  [
    [
      [false, false, false, false, false],
      [false, true, true, true, false],
      [false, true, true, false, true],
      [false, true, false, true, false],
      [false, false, true, false, false],
    ],
    "28",
    "Corners Oriented",
    "r U R' U' r' R U R U' R'",

  ],
  [
    [
      [false, false, true, false, false],
      [false, true, false, true, false],
      [false, true, true, true, false],
      [false, true, false, true, false],
      [false, false, true, false, false],
    ],
    "57",
    "Corners Oriented",
    "R U R' U' M' U R U' r'"
  ],
  [
    [
      [false, true, false, true, false],
      [false, false, true, false, false],
      [false, true, true, true, false],
      [false, false, true, false, false],
      [false, true, false, true, false],
    ],
    "21",
    "Cross",
    "R U2 R' U' R U R' U' R U' R'",

  ],
  [
    [
      [false, false, false, true, false],
      [true, false, true, false, false],
      [false, true, true, true, false],
      [true, false, true, false, false],
      [false, false, false, true, false],
    ],
    "22",
    "Cross",
    "R U2 R2 U' R2 U' R2 U2 R",
  ],
  [
    [
      [false, true, false, true, false],
      [false, false, true, false, false],
      [false, true, true, true, false],
      [false, true, true, true, false],
      [false, false, false, false, false],
    ],
    "23",
    "Cross",
    "R2 D' R U2 R' D R U2 R",

  ],
  [
    [
      [false, true, false, false, false],
      [false, false, true, true, false],
      [false, true, true, true, false],
      [false, false, true, true, false],
      [false, true, false, false, false],
    ],
    "24",
    "Cross",
    "r U R' U' r' F R F'",
  ],
  [
    [
      [false, false, false, false, false],
      [true, false, true, true, false],
      [false, true, true, true, false],
      [false, true, true, false, false],
      [false, false, false, true, false],
    ],
    "25",
    "Cross",
    "F' r U R' U' r' F R",

  ],
  [
    [
      [false, false, false, false, false],
      [true, false, true, true, false],
      [false, true, true, true, false],
      [false, false, true, false, true],
      [false, true, false, false, false],
    ],
    "26",
    "Cross",
    "R U2 R' U' R U' R'",
  ],
  [
    [
      [false, true, false, false, false],
      [false, false, true, false, true],
      [false, true, true, true, false],
      [false, true, true, false, false],
      [false, false, false, true, false],
    ],
    "27",
    "Cross",
    "R U R' U R U2 R'",
  ],
  [
    [
      [false, false, true, false, false],
      [true, false, false, false, true],
      [true, false, true, false, true],
      [true, false, false, false, true],
      [false, false, true, false, false],
    ],
    "1",
    "Dot",
    "R U2 R2 F R F' U2 R' F R F'",
  ],
  [
    [
      [false, true, true, true, false],
      [false, false, false, false, false],
      [true, false, true, false, true],
      [true, false, false, false, true],
      [false, false, true, false, false],
    ],
    "2",
    "Dot",
    "r U r' U2 r U2 R' U2 R U' r'",
  ],
  [
    [
      [false, true, true, false, false],
      [false, false, false, false, true],
      [true, false, true, false, true],
      [false, true, false, false, false],
      [false, false, true, true, false],
    ],
    "3",
    "Dot",
    "r' R2 U R' U r U2 r' U M'",
  ],
  [
    [
      [false, false, true, true, false],
      [true, false, false, false, false],
      [true, false, true, false, true],
      [false, false, false, true, false],
      [false, true, true, false, false],
    ],
    "4",
    "Dot",
    "M U' r U2 r' U' R U' R' M'",
  ],
  [
    [
      [false, false, true, false, false],
      [false, true, false, false, true],
      [true, false, true, false, true],
      [false, false, false, true, false],
      [false, true, true, false, false],
    ],
    "17",
    "Dot",
    "F R' F' R2 r' U R U' R' U' M'",
  ],
  [
    [
      [false, false, true, false, false],
      [false, true, false, true, false],
      [true, false, true, false, true],
      [false, false, false, false, false],
      [false, true, true, true, false],
    ],
    "18",
    "Dot",
    "r U R' U R U2 r2 U' R U' R' U2 r",
  ],
  [
    [
      [false, false, true, false, false],
      [false, true, false, true, false],
      [true, false, true, false, true],
      [true, false, false, false, true],
      [false, false, true, false, false],
    ],
    "19",
    "Dot",
    "r' R U R U R' U' M' R' F R F'",
  ],
  [
    [
      [false, false, true, false, false],
      [false, true, false, true, false],
      [true, false, true, false, true],
      [false, true, false, true, false],
      [false, false, true, false, false],
    ],
    "20",
    "Dot",
    "r U R' U' M2 U R U' R' U' M'",
  ],
  [
    [
      [false, false, false, true, false],
      [true, false, true, false, false],
      [false, true, true, false, true],
      [false, false, false, true, false],
      [false, true, true, false, false],
    ],
    "9",
    "Fish Shape",
    "R U R' U' R' F R2 U R' U' F'",
  ],
  [
    [
      [false, true, true, false, false],
      [false, false, false, true, false],
      [false, true, true, false, true],
      [true, false, true, false, false],
      [false, false, false, true, false],
    ],
    "10",
    "Fish Shape",
    "R U R' U R' F R F' R U2 R'",
  ],
  [
    [
      [false, false, true, false, false],
      [false, true, false, false, true],
      [true, false, true, true, false],
      [false, false, true, true, false],
      [false, true, false, false, false],
    ],
    "35",
    "Fish Shape",
    "R U2 R2 F R F' R U2 R'",
  ],
  [
    [
      [false, false, false, false, false],
      [false, true, true, false, true],
      [false, true, true, false, true],
      [false, false, false, true, false],
      [false, true, true, false, false],
    ],
    "37",
    "Fish Shape",
    "F R' F' R U R U' R'",
  ],
  [
    [
      [false, true, true, false, false],
      [false, false, false, false, true],
      [false, true, true, true, false],
      [false, false, false, false, true],
      [false, true, true, false, false],
    ],
    "51",
    "I Shape",
    "F U R U' R' U R U' R' F'",
  ],
  [
    [
      [false, true, false, false, false],
      [false, false, true, false, true],
      [true, false, true, false, true],
      [false, false, true, false, true],
      [false, true, false, false, false],
    ],
    "52",
    "I Shape",
    "R U R' U R U' B U' B' R'",
  ],
  [
    [
      [false, true, true, true, false],
      [false, false, false, false, false],
      [false, true, true, true, false],
      [false, false, false, false, false],
      [false, true, true, true, false],
    ],
    "55",
    "I Shape",
    "R' F R U R U' R2 F' R2 U' R' U R U R'",
  ],
  [
    [
      [false, false, true, false, false],
      [true, false, false, false, true],
      [false, true, true, true, false],
      [true, false, false, false, true],
      [false, false, true, false, false],
    ],
    "56",
    "I Shape",
    "r' U' r U' R' U R U' R' U R r' U r",
  ],
  [
    [
      [false, true, true, true, false],
      [false, false, false, false, false],
      [false, true, true, true, false],
      [false, true, false, false, false],
      [false, false, true, true, false],
    ],
    "13",
    "Knight Move Shape",
    "F U R U' R2 F' R U R U' R'",
  ],
  [
    [
      [false, false, true, true, false],
      [true, false, false, false, false],
      [false, true, true, true, false],
      [false, false, false, true, false],
      [false, true, true, false, false],
    ],
    "14",
    "Knight Move Shape",
    "R' F R U R' F' R F U' F'",
  ],
  [
    [
      [false, false, true, false, false],
      [false, true, false, false, true],
      [false, true, true, true, false],
      [true, false, false, false, false],
      [false, false, true, true, false],
    ],
    "15",
    "Knight Move Shape",
    "l' U' l L' U' L U l' U l",
  ],
  [
    [
      [false, false, true, false, false],
      [true, false, false, true, false],
      [false, true, true, true, false],
      [false, false, false, false, true],
      [false, true, true, false, false],
    ],
    "16",
    "Knight Move Shape",
    "r U r' R U R' U' r U' r'",
  ],
  [
    [
      [false, true, false, false, false],
      [false, false, true, true, false],
      [true, false, true, true, false],
      [false, false, false, true, false],
      [false, true, true, false, false],
    ],
    "31",
    "P Shape",
    "R' U' F U R U' R' F' R",
  ],
  [
    [
      [false, false, false, true, false],
      [false, true, true, false, false],
      [false, true, true, false, true],
      [false, true, false, false, false],
      [false, false, true, true, false],
    ],
    "32",
    "P Shape",
    "L U F' U' L' U L F L'",
  ],
  [
    [
      [false, false, false, false, false],
      [true, false, true, true, false],
      [true, false, true, true, false],
      [true, false, false, true, false],
      [false, false, true, false, false],
    ],
    "43",
    "P Shape",
    "F' U' L' U L F",
  ],
  [
    [
      [false, false, false, false, false],
      [false, true, true, false, true],
      [false, true, true, false, true],
      [false, true, false, false, true],
      [false, false, true, false, false],
    ],
    "44",
    "P Shape",
    "F U R U' R' F'",
  ],
  [
    [
      [false, true, false, false, false],
      [false, false, true, false, true],
      [true, false, true, true, false],
      [false, false, false, false, true],
      [false, true, true, false, false],
    ],
    "47",
    "Small L Shape",
    "R' U' R' F R F' R' F R F' U R",
  ],
  [
    [
      [false, false, false, true, false],
      [true, false, true, false, false],
      [false, true, true, false, true],
      [true, false, false, false, false],
      [false, false, true, true, false],
    ],
    "48",
    "Small L Shape",
    "F R U R' U' R U R' U' F'",
  ],
  [
    [
      [false, false, false, true, false],
      [true, false, true, false, false],
      [true, false, true, true, false],
      [true, false, false, false, false],
      [false, false, true, true, false],
    ],
    "49",
    "Small L Shape",
    "r U' r2 U r2 U r2 U' r",
  ],
  [
    [
      [false, false, true, true, false],
      [true, false, false, false, false],
      [true, false, true, true, false],
      [true, false, true, false, false],
      [false, false, false, true, false],
    ],
    "50",
    "Small L Shape",
    "r' U r2 U' r2 U' r2 U r'",
  ],
  [
    [
      [false, true, false, true, false],
      [false, false, true, false, false],
      [true, false, true, true, false],
      [false, false, false, false, false],
      [false, true, true, true, false],
    ],
    "53",
    "Small L Shape",
    "l' U2 L U L' U' L U L' U l",
  ],
  [
    [
      [false, true, false, true, false],
      [false, false, true, false, false],
      [false, true, true, false, true],
      [false, false, false, false, false],
      [false, true, true, true, false],
    ],
    "54",
    "Small L Shape",
    "r U2 R' U' R U R' U' R U' r'",
  ],
  [
    [
      [false, true, false, false, false],
      [false, false, true, false, true],
      [false, true, true, false, true],
      [false, true, false, false, false],
      [false, false, true, true, false],
    ],
    "7",
    "Small Lightning Bolt",
    "r U R' U R U2 r'",
  ],
  [
    [
      [false, false, false, true, false],
      [true, false, true, false, false],
      [true, false, true, true, false],
      [false, false, false, true, false],
      [false, true, true, false, false],
    ],
    "8",
    "Small Lightning Bolt",
    "l' U' L U' L' U2 l",
  ],
  [
    [
      [false, true, false, false, false],
      [false, false, true, true, false],
      [false, true, true, false, true],
      [true, false, false, false, false],
      [false, false, true, true, false],
    ],
    "11",
    "Small Lightning Bolt",
    "r U R' U R' F R F' R U2 r'",
  ],
  [
    [
      [false, false, false, true, false],
      [false, true, true, false, false],
      [true, false, true, true, false],
      [false, false, false, false, true],
      [false, true, true, false, false],
    ],
    "12",
    "Small Lightning Bolt",
    "M' R' U' R U' R' U2 R U' R r'",
  ],
  [
    [
      [false, false, false, false, false],
      [false, true, true, false, true],
      [false, true, true, false, true],
      [true, false, false, false, false],
      [false, false, true, true, false],
    ],
    "5",
    "Square Shape",
    "l' U2 L U L' U l",
  ],
  [
    [
      [false, false, false, false, false],
      [true, false, true, true, false],
      [true, false, true, true, false],
      [false, false, false, false, true],
      [false, true, true, false, false],
    ],
    "6",
    "Square Shape",
    "r U2 R' U' R U' r'",
  ],
  [
    [
      [false, true, true, false, false],
      [false, false, false, true, false],
      [false, true, true, true, false],
      [false, false, false, true, false],
      [false, true, true, false, false],
    ],
    "33",
    "T Shape",
    "R U R' U' R' F R F'",
  ],
  [
    [
      [false, false, true, false, false],
      [true, false, false, true, false],
      [false, true, true, true, false],
      [true, false, false, true, false],
      [false, false, true, false, false],
    ],
    "45",
    "T Shape",
    "F R U R' U' F'",
  ],
  [
    [
      [false, false, false, true, false],
      [false, true, true, false, false],
      [true, false, true, true, false],
      [true, false, false, true, false],
      [false, false, true, false, false],
    ],
    "36",
    "W Shape",
    "L' U' L U' L' U L U L F' L' F",
  ],
  [
    [
      [false, true, false, false, false],
      [false, false, true, true, false],
      [false, true, true, false, true],
      [false, true, false, false, true],
      [false, false, true, false, false],
    ],
    "38",
    "W Shape",
    "R U R' U R U' R' U' R' F R F'",
  ],
];